from __future__ import annotations

import math

import numpy as np
from PIL import Image

from .config import PREVIEW_MAX_WIDTH
from .inputs import center_crop_to_common_size

ZONE_DIAGNOSTICS_GRID = 3
ZONE_PROBE_ID = "pipeline_basis_v1_y_ransac"
ZONE3X3_LABELS = [
    "oben_links", "oben_mitte", "oben_rechts",
    "mitte_links", "mitte", "mitte_rechts",
    "unten_links", "unten_mitte", "unten_rechts",
]

Y_RESIDUAL_MIN_TOTAL_POINTS = 30
Y_RESIDUAL_MIN_TRAIN_POINTS_PER_PARAMETER = 6
Y_RESIDUAL_MIN_RELIABLE_ZONES = 5
Y_RESIDUAL_MIN_RELIABLE_ZONE_POINTS = 10
Y_RESIDUAL_ZONE_SOFT_CAP_PER_ZONE = 80
Y_RESIDUAL_HOLDOUT_STRIDE = 5
Y_RESIDUAL_MAX_CORRECTION_FRACTION = 0.018
Y_RESIDUAL_MAX_CORRECTION_ANALYSIS_PX = 24.0
Y_RESIDUAL_APPLY_MODEL_NAME = "y_quad"

TRAPEZ_MIN_TOTAL_INLIERS = 40
TRAPEZ_HOLDOUT_STRIDE = 5
TRAPEZ_MIN_TRAIN_POINTS = 24
TRAPEZ_MAX_DESIGN_CONDITION = 1.0e6
TRAPEZ_ZONE_SOFT_CAP_PER_ZONE = 80
TRAPEZ_HARD_MAX_PARAM_ABS = 0.75
TRAPEZ_HARD_MIN_DENOMINATOR = 0.35
TRAPEZ_WARNING_MAX_PARAM_ABS = 0.12
TRAPEZ_WARNING_MIN_DENOMINATOR = 0.86
TRAPEZ_WARNING_MAX_CORNER_SHIFT_PERMILLE = 45.0
TRAPEZ_WARNING_MAX_EDGE_STRETCH_PERCENT = 7.5

Y_RESIDUAL_MODEL_SPECS = {
    "y_quad": ["constant", "x", "y", "xy", "x2", "y2"],
}

def _largest_all_valid_rectangle(valid: np.ndarray) -> tuple[int, int, int, int] | None:
    """Return the largest axis-aligned rectangle fully inside a valid mask.

    The mask is generated by warping an all-white source mask with the same
    affine transform as the right image. Therefore every True pixel represents
    real source image content after the warp.
    
    Coordinates are x0, y0, x1, y1 with x1/y1 exclusive.
    """
    if valid.ndim != 2 or not valid.any():
        return None

    h, w = valid.shape
    heights = [0] * w
    best_area = 0
    best_rect = None

    for y in range(h):
        row = valid[y]
        for x in range(w):
            heights[x] = heights[x] + 1 if row[x] else 0

        stack = []
        for x in range(w + 1):
            current_height = heights[x] if x < w else 0

            while stack and heights[stack[-1]] > current_height:
                height = heights[stack.pop()]
                x0 = stack[-1] + 1 if stack else 0
                x1 = x
                width = x1 - x0
                area = height * width

                if area > best_area:
                    best_area = area
                    y1 = y + 1
                    y0 = y1 - height
                    best_rect = (x0, y0, x1, y1)

            stack.append(x)

    if best_rect is None:
        return None

    x0, y0, x1, y1 = best_rect

    # Deterministic safety margin against interpolation fringes at the exact
    # border of the warped image. This is not a crop heuristic; it is a fixed
    # one-pixel guard band around a mathematically valid rectangle.
    margin = 2
    if x1 - x0 > margin * 2 and y1 - y0 > margin * 2:
        x0 += margin
        y0 += margin
        x1 -= margin
        y1 -= margin

    if x1 - x0 <= 2 or y1 - y0 <= 2:
        return None

    return x0, y0, x1, y1

def resize_array_for_preview(arr: np.ndarray, scale: float) -> np.ndarray:
    if scale >= 0.999:
        return arr

    height, width = arr.shape[:2]
    new_width = max(1, round(width * scale))
    new_height = max(1, round(height * scale))

    img = Image.fromarray(arr, "RGB")
    img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
    return np.asarray(img, dtype=np.uint8)

def resize_pair_for_preview(
    left: np.ndarray,
    right: np.ndarray,
    max_width: int,
    max_height: int,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Create a fast working copy for live preview rendering.

    The returned scale maps original half-image pixels to preview pixels.
    Full-resolution export can later use the same offsets on the originals.
    """
    lh, lw = left.shape[:2]
    rh, rw = right.shape[:2]

    common_w = max(1, min(lw, rw))
    common_h = max(1, min(lh, rh))

    scale = min(
        max_width / common_w,
        max_height / common_h,
        PREVIEW_MAX_WIDTH / common_w,
        1.0,
    )

    return (
        resize_array_for_preview(left, scale),
        resize_array_for_preview(right, scale),
        scale,
    )

def resize_pair_for_analysis(
    left: np.ndarray,
    right: np.ndarray,
    max_width: int,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Create grayscale analysis images limited by half-image width."""
    lh, lw = left.shape[:2]
    rh, rw = right.shape[:2]

    common_w = max(1, min(lw, rw))
    scale = min(max_width / common_w, 1.0)

    left_small = resize_array_for_preview(left, scale)
    right_small = resize_array_for_preview(right, scale)

    left_gray = np.asarray(Image.fromarray(left_small, "RGB").convert("L"), dtype=np.uint8)
    right_gray = np.asarray(Image.fromarray(right_small, "RGB").convert("L"), dtype=np.uint8)

    return left_gray, right_gray, scale

def _transform_points(matrix: np.ndarray, points: np.ndarray) -> np.ndarray:
    pts = points.reshape(-1, 2).astype(np.float64)
    matrix = np.asarray(matrix, dtype=np.float64)

    if matrix.shape == (3, 3):
        ones = np.ones((pts.shape[0], 1), dtype=np.float64)
        hom = np.hstack([pts, ones]) @ matrix.T
        denom = hom[:, 2:3]
        denom[np.abs(denom) < 1e-12] = 1e-12
        return hom[:, :2] / denom

    ones = np.ones((pts.shape[0], 1), dtype=np.float64)
    hom = np.hstack([pts, ones])
    return hom @ matrix.reshape(2, 3).T

def _point_coverage_percent(points: np.ndarray, image_shape: tuple[int, int]) -> float:
    pts = points.reshape(-1, 2)
    if len(pts) < 3:
        return 0.0

    h, w = image_shape[:2]
    x0, y0 = np.min(pts, axis=0)
    x1, y1 = np.max(pts, axis=0)
    area = max(0.0, float(x1 - x0)) * max(0.0, float(y1 - y0))
    image_area = max(1.0, float(w * h))
    return float(np.clip(area / image_area * 100.0, 0.0, 100.0))

def _grid_zone_indices(points: np.ndarray, image_shape: tuple[int, int], grid: int = 3) -> np.ndarray:
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    h, w = image_shape[:2]
    if len(pts) == 0 or h <= 0 or w <= 0:
        return np.zeros((len(pts),), dtype=np.int32)
    x = np.clip(pts[:, 0], 0.0, max(0.0, float(w) - 1.0))
    y = np.clip(pts[:, 1], 0.0, max(0.0, float(h) - 1.0))
    col = np.clip((x / max(1.0, float(w)) * grid).astype(np.int32), 0, grid - 1)
    row = np.clip((y / max(1.0, float(h)) * grid).astype(np.int32), 0, grid - 1)
    return row * grid + col

def _grid_zone_counts(points: np.ndarray, image_shape: tuple[int, int], grid: int = 3) -> list[int]:
    zones = _grid_zone_indices(points, image_shape, grid)
    return [int(np.sum(zones == idx)) for idx in range(grid * grid)]

def _zone_balanced_weights(points: np.ndarray, image_shape: tuple[int, int], grid: int = 3) -> np.ndarray:
    """Give each occupied 3x3 zone the same total influence.

    Dense zones therefore do not dominate the least-squares solve just because
    they contain many more feature matches. The final weights are normalized to
    a mean value of 1.0 so ordinary and weighted LMS stay numerically similar.
    """
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    n = len(pts)
    if n == 0:
        return np.zeros((0,), dtype=np.float64)
    zones = _grid_zone_indices(pts, image_shape, grid)
    weights = np.zeros((n,), dtype=np.float64)
    for idx in range(grid * grid):
        mask = zones == idx
        count = int(np.sum(mask))
        if count > 0:
            weights[mask] = 1.0 / float(count)
    total = float(np.sum(weights))
    if total > 1e-12:
        weights *= float(n) / total
    else:
        weights[:] = 1.0
    return weights

def _zone_capped_weights(
    points: np.ndarray,
    image_shape: tuple[int, int],
    grid: int = 3,
    cap_per_zone: int = Y_RESIDUAL_ZONE_SOFT_CAP_PER_ZONE,
) -> np.ndarray:
    """Softly prevent dense zones from dominating a residual-model fit.

    Unlike hard zone balancing, sparse zones are not boosted to the same total
    influence as dense zones.  Dense zones are merely capped: if a zone contains
    more than `cap_per_zone` points, every point in that zone is down-weighted so
    the zone contributes roughly `cap_per_zone` effective points.  This keeps a
    reliable centre from overpowering the fit while avoiding the earlier problem
    where thin edge zones received too much authority.
    """
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    n = len(pts)
    if n == 0:
        return np.zeros((0,), dtype=np.float64)
    zones = _grid_zone_indices(pts, image_shape, grid)
    weights = np.ones((n,), dtype=np.float64)
    cap = max(1, int(cap_per_zone))
    for idx in range(grid * grid):
        mask = zones == idx
        count = int(np.sum(mask))
        if count > cap:
            weights[mask] = float(cap) / float(count)
    mean = float(np.mean(weights))
    if mean > 1e-12:
        weights /= mean
    return weights

def _safe_corrcoef(a: np.ndarray, b: np.ndarray) -> float | None:
    aa = np.asarray(a, dtype=np.float64).reshape(-1)
    bb = np.asarray(b, dtype=np.float64).reshape(-1)
    n = min(len(aa), len(bb))
    if n < 4:
        return None
    aa = aa[:n]
    bb = bb[:n]
    mask = np.isfinite(aa) & np.isfinite(bb)
    if int(np.sum(mask)) < 4:
        return None
    aa = aa[mask]
    bb = bb[mask]
    if float(np.std(aa)) <= 1e-12 or float(np.std(bb)) <= 1e-12:
        return None
    return float(np.corrcoef(aa, bb)[0, 1])

def _y_residual_design_matrix(
    left_points_after_affine: np.ndarray,
    right_points_after_affine: np.ndarray,
    image_shape: tuple[int, int],
    terms: list[str],
) -> tuple[np.ndarray, list[str]]:
    """Build a low-order y-residual design matrix.

    x/y are normalized image coordinates after Affine-LMS.  `disp` is the
    centered horizontal disparity after Affine-LMS and is included only as a
    diagnostic predictor: it may explain depth-linked vertical residuals, but it
    is not itself a stereo-safe x-error target.
    """
    left_pts = np.asarray(left_points_after_affine, dtype=np.float64).reshape(-1, 2)
    right_pts = np.asarray(right_points_after_affine, dtype=np.float64).reshape(-1, 2)
    n = min(len(left_pts), len(right_pts))
    left_pts = left_pts[:n]
    right_pts = right_pts[:n]
    h, w = image_shape[:2]
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0
    x = (left_pts[:, 0] - cx) / max(1.0, float(w))
    y = (left_pts[:, 1] - cy) / max(1.0, float(h))
    disp = right_pts[:, 0] - left_pts[:, 0]
    disp = disp - float(np.median(disp)) if len(disp) else disp
    disp = disp / max(1.0, float(w))

    columns: list[np.ndarray] = []
    labels: list[str] = []
    for term in terms:
        if term == "constant":
            columns.append(np.ones((n,), dtype=np.float64))
        elif term == "x":
            columns.append(x)
        elif term == "y":
            columns.append(y)
        elif term == "xy":
            columns.append(x * y)
        elif term == "x2":
            columns.append((x * x) - float(np.mean(x * x)) if n else x * x)
        elif term == "y2":
            columns.append((y * y) - float(np.mean(y * y)) if n else y * y)
        elif term == "disp":
            columns.append(disp)
        else:
            raise ValueError(f"Unbekannter y-Restmodell-Term: {term}")
        labels.append(term)
    if not columns:
        return np.zeros((n, 0), dtype=np.float64), []
    return np.column_stack(columns), labels

def _holdout_mask_for_residual_basis(points: np.ndarray, stride: int = Y_RESIDUAL_HOLDOUT_STRIDE) -> np.ndarray:
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    n = len(pts)
    if n == 0:
        return np.zeros((0,), dtype=bool)
    stride = max(3, int(stride))
    # Sort spatially before taking every nth point.  This makes the holdout more
    # image-distributed than simply using descriptor order.
    order = np.lexsort((pts[:, 0], pts[:, 1]))
    eval_mask = np.zeros((n,), dtype=bool)
    eval_mask[order[::stride]] = True
    if int(np.sum(eval_mask)) < max(8, n // (stride + 1)):
        eval_mask[:] = False
        eval_mask[::stride] = True
    if int(np.sum(eval_mask)) >= n - 4:
        eval_mask[:] = False
        eval_mask[::stride] = True
    return eval_mask

def _residual_model_support_summary(points: np.ndarray, image_shape: tuple[int, int]) -> dict:
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    counts = _grid_zone_counts(pts, image_shape, ZONE_DIAGNOSTICS_GRID)
    reliable = [c for c in counts if int(c) >= Y_RESIDUAL_MIN_RELIABLE_ZONE_POINTS]
    return {
        "total_points": int(len(pts)),
        "grid": int(ZONE_DIAGNOSTICS_GRID),
        "counts": [int(c) for c in counts],
        "occupied_zones": int(sum(1 for c in counts if int(c) > 0)),
        "reliable_zone_min_points": int(Y_RESIDUAL_MIN_RELIABLE_ZONE_POINTS),
        "reliable_zones": int(len(reliable)),
        "min_required_reliable_zones": int(Y_RESIDUAL_MIN_RELIABLE_ZONES),
        "zone_soft_cap_per_zone": int(Y_RESIDUAL_ZONE_SOFT_CAP_PER_ZONE),
    }

def _fit_y_residual_candidate(
    name: str,
    terms: list[str],
    left_points_after_affine: np.ndarray,
    right_points_after_affine: np.ndarray,
    affine_vertical_signed_analysis: np.ndarray,
    image_shape: tuple[int, int],
    analysis_scale: float,
) -> dict:
    left_pts = np.asarray(left_points_after_affine, dtype=np.float64).reshape(-1, 2)
    right_pts = np.asarray(right_points_after_affine, dtype=np.float64).reshape(-1, 2)
    residual = np.asarray(affine_vertical_signed_analysis, dtype=np.float64).reshape(-1)
    n = min(len(left_pts), len(right_pts), len(residual))
    left_pts = left_pts[:n]
    right_pts = right_pts[:n]
    residual = residual[:n]

    support = _residual_model_support_summary(left_pts, image_shape)
    matrix, labels = _y_residual_design_matrix(left_pts, right_pts, image_shape, terms)
    # Store the exact normalization used by the design matrix so the visual
    # apply basis can evaluate the same low-order field on a full-resolution
    # image grid.  The x²/y² columns are centred on the matched-point
    # distribution, not on a theoretical whole-image average.
    h_norm, w_norm = image_shape[:2]
    cx_norm = (float(w_norm) - 1.0) / 2.0
    cy_norm = (float(h_norm) - 1.0) / 2.0
    if n:
        x_norm_values = (left_pts[:, 0] - cx_norm) / max(1.0, float(w_norm))
        y_norm_values = (left_pts[:, 1] - cy_norm) / max(1.0, float(h_norm))
        disp_values = right_pts[:, 0] - left_pts[:, 0]
        normalization = {
            "x2_mean": float(np.mean(x_norm_values * x_norm_values)),
            "y2_mean": float(np.mean(y_norm_values * y_norm_values)),
            "disp_median_analysis_px": float(np.median(disp_values)),
            "analysis_width": int(w_norm),
            "analysis_height": int(h_norm),
        }
    else:
        normalization = {
            "x2_mean": 0.0,
            "y2_mean": 0.0,
            "disp_median_analysis_px": 0.0,
            "analysis_width": int(w_norm),
            "analysis_height": int(h_norm),
        }
    param_count = matrix.shape[1]
    eval_mask = _holdout_mask_for_residual_basis(left_pts, Y_RESIDUAL_HOLDOUT_STRIDE)
    train_mask = ~eval_mask
    if int(np.sum(train_mask)) < max(param_count + 4, param_count * Y_RESIDUAL_MIN_TRAIN_POINTS_PER_PARAMETER):
        train_mask[:] = True
        eval_mask[:] = False

    ready = (
        n >= Y_RESIDUAL_MIN_TOTAL_POINTS
        and param_count > 0
        and int(np.sum(train_mask)) >= max(param_count + 4, param_count * Y_RESIDUAL_MIN_TRAIN_POINTS_PER_PARAMETER)
        and support["reliable_zones"] >= Y_RESIDUAL_MIN_RELIABLE_ZONES
    )

    max_abs_model = min(
        float(Y_RESIDUAL_MAX_CORRECTION_ANALYSIS_PX),
        float(Y_RESIDUAL_MAX_CORRECTION_FRACTION) * float(max(1, min(image_shape[:2]))),
    )

    if not ready:
        beta = np.zeros((param_count,), dtype=np.float64)
        model = np.zeros((n,), dtype=np.float64)
    else:
        weights = _zone_capped_weights(left_pts, image_shape, ZONE_DIAGNOSTICS_GRID, Y_RESIDUAL_ZONE_SOFT_CAP_PER_ZONE)
        beta = _weighted_lstsq(matrix[train_mask], residual[train_mask], weights[train_mask])
        model = matrix @ beta
        model = np.clip(model, -max_abs_model, max_abs_model)

    corrected = residual - model
    eval_indices = np.where(eval_mask)[0]
    if len(eval_indices) == 0:
        eval_indices = np.arange(n, dtype=np.int64)
        eval_note = "no_holdout_available_eval_uses_all_points"
    else:
        eval_note = "spatial_holdout"

    def local_summary(values: np.ndarray) -> dict:
        signed_px = np.asarray(values, dtype=np.float64).reshape(-1) / max(1e-12, float(analysis_scale))
        if len(signed_px) == 0:
            return {"mean_signed": None, "mean_abs": None, "median_abs": None, "p90_abs": None, "p95_abs": None, "max_abs": None}
        abs_px = np.abs(signed_px)
        return {
            "mean_signed": float(np.mean(signed_px)),
            "mean_abs": float(np.mean(abs_px)),
            "median_abs": float(np.median(abs_px)),
            "p90_abs": float(np.percentile(abs_px, 90)),
            "p95_abs": float(np.percentile(abs_px, 95)),
            "max_abs": float(np.max(abs_px)),
        }

    coefficient_rows = []
    for label, value in zip(labels, beta.tolist()):
        coefficient_rows.append({
            "term": label,
            "coefficient_analysis_px": float(value),
            "coefficient_fullres_px_approx": float(value) / max(1e-12, float(analysis_scale)),
        })

    return {
        "name": name,
        "terms": labels,
        "ready": bool(ready),
        "support": support,
        "train_points": int(np.sum(train_mask)),
        "eval_points": int(len(eval_indices)),
        "eval_mode": eval_note,
        "max_abs_model_analysis_px": float(max_abs_model),
        "max_abs_model_fullres_px": float(max_abs_model) / max(1e-12, float(analysis_scale)),
        "coefficients": coefficient_rows,
        "normalization": normalization,
        "model_summary": local_summary(model),
        "vertical": local_summary(corrected),
        "vertical_holdout": local_summary(corrected[eval_indices]),
        "baseline_holdout": local_summary(residual[eval_indices]),
        "zone3x3": _vertical_residual_zone_stats(left_pts, corrected, image_shape, analysis_scale, ZONE_DIAGNOSTICS_GRID),
        "zone3x3_holdout": _vertical_residual_zone_stats(left_pts[eval_indices], corrected[eval_indices], image_shape, analysis_scale, ZONE_DIAGNOSTICS_GRID),
        "vs_affine": None,  # filled by the caller because it needs affine zone stats
        "vs_affine_holdout_mean_abs_delta": None,
    }

def _weighted_lstsq(a: np.ndarray, target: np.ndarray, weights: np.ndarray | None) -> np.ndarray:
    if weights is None:
        params, *_ = np.linalg.lstsq(a, target, rcond=None)
        return params
    w = np.asarray(weights, dtype=np.float64).reshape(-1)
    if len(w) != len(target) or not np.all(np.isfinite(w)) or float(np.sum(w)) <= 1e-12:
        params, *_ = np.linalg.lstsq(a, target, rcond=None)
        return params
    sw = np.sqrt(np.clip(w, 0.0, None))
    params, *_ = np.linalg.lstsq(a * sw[:, None], target * sw, rcond=None)
    return params

def _vertical_residual_zone_stats(
    anchor_points: np.ndarray,
    vertical_residual_signed_analysis: np.ndarray,
    image_shape: tuple[int, int],
    analysis_scale: float,
    grid: int = 3,
) -> dict:
    pts = np.asarray(anchor_points, dtype=np.float64).reshape(-1, 2)
    signed = np.asarray(vertical_residual_signed_analysis, dtype=np.float64).reshape(-1)
    n = min(len(pts), len(signed))
    pts = pts[:n]
    signed = signed[:n]
    if n == 0:
        labels = ZONE3X3_LABELS if grid == 3 else [str(i) for i in range(grid * grid)]
        return {
            "grid": int(grid),
            "labels": labels,
            "zones": [],
            "occupied_zones": 0,
            "mean_abs": None,
            "median_abs": None,
            "p90_abs": None,
            "p95_abs": None,
            "max_abs": None,
            "worst_zone_label": None,
            "worst_zone_mean_abs": None,
        }

    scale = max(1e-12, float(analysis_scale))
    signed_px = signed / scale
    abs_px = np.abs(signed_px)
    zones = _grid_zone_indices(pts, image_shape, grid)
    labels = ZONE3X3_LABELS if grid == 3 else [str(i) for i in range(grid * grid)]

    zone_rows = []
    occupied = 0
    worst_label = None
    worst_mean = None
    for idx in range(grid * grid):
        mask = zones == idx
        count = int(np.sum(mask))
        label = labels[idx] if idx < len(labels) else str(idx)
        if count == 0:
            zone_rows.append({
                "label": label,
                "count": 0,
                "mean_signed": None,
                "mean_abs": None,
                "median_abs": None,
                "p90_abs": None,
                "max_abs": None,
            })
            continue
        occupied += 1
        signed_zone = signed_px[mask]
        abs_zone = abs_px[mask]
        mean_abs = float(np.mean(abs_zone))
        if worst_mean is None or mean_abs > worst_mean:
            worst_mean = mean_abs
            worst_label = label
        zone_rows.append({
            "label": label,
            "count": count,
            "mean_signed": float(np.mean(signed_zone)),
            "mean_abs": mean_abs,
            "median_abs": float(np.median(abs_zone)),
            "p90_abs": float(np.percentile(abs_zone, 90)),
            "max_abs": float(np.max(abs_zone)),
        })

    def mean_for_indices(indices: list[int]) -> float | None:
        mask = np.isin(zones, indices)
        if int(np.sum(mask)) == 0:
            return None
        return float(np.mean(abs_px[mask]))

    return {
        "grid": int(grid),
        "labels": labels,
        "zones": zone_rows,
        "occupied_zones": int(occupied),
        "counts": [row["count"] for row in zone_rows],
        "mean_abs": float(np.mean(abs_px)),
        "median_abs": float(np.median(abs_px)),
        "p90_abs": float(np.percentile(abs_px, 90)),
        "p95_abs": float(np.percentile(abs_px, 95)),
        "max_abs": float(np.max(abs_px)),
        "worst_zone_label": worst_label,
        "worst_zone_mean_abs": worst_mean,
        "top_mean_abs": mean_for_indices([0, 1, 2]),
        "middle_mean_abs": mean_for_indices([3, 4, 5]),
        "bottom_mean_abs": mean_for_indices([6, 7, 8]),
        "left_mean_abs": mean_for_indices([0, 3, 6]),
        "center_col_mean_abs": mean_for_indices([1, 4, 7]),
        "right_mean_abs": mean_for_indices([2, 5, 8]),
        "corner_mean_abs": mean_for_indices([0, 2, 6, 8]),
        "edge_mean_abs": mean_for_indices([0, 1, 2, 3, 5, 6, 7, 8]),
        "center_zone_mean_abs": mean_for_indices([4]),
    }

def _zone_improvement_stats(before: dict, after: dict, epsilon_px: float = 0.01) -> dict:
    before_zones = {z.get("label"): z for z in before.get("zones", [])}
    after_zones = {z.get("label"): z for z in after.get("zones", [])}
    rows = []
    improved = 0
    worsened = 0
    unchanged = 0
    worst_worsening_label = None
    worst_worsening = None
    best_improvement_label = None
    best_improvement = None
    for label, b in before_zones.items():
        a = after_zones.get(label)
        if not a:
            continue
        b_mean = b.get("mean_abs")
        a_mean = a.get("mean_abs")
        if b_mean is None or a_mean is None:
            continue
        delta = float(a_mean) - float(b_mean)
        if delta < -epsilon_px:
            improved += 1
        elif delta > epsilon_px:
            worsened += 1
        else:
            unchanged += 1
        if worst_worsening is None or delta > worst_worsening:
            worst_worsening = delta
            worst_worsening_label = label
        if best_improvement is None or delta < best_improvement:
            best_improvement = delta
            best_improvement_label = label
        rows.append({"label": label, "delta_mean_abs": delta})
    return {
        "epsilon_px": float(epsilon_px),
        "zones_compared": len(rows),
        "improved_zones": int(improved),
        "worsened_zones": int(worsened),
        "unchanged_zones": int(unchanged),
        "worst_worsening_label": worst_worsening_label,
        "worst_worsening_delta": worst_worsening,
        "best_improvement_label": best_improvement_label,
        "best_improvement_delta": best_improvement,
        "zone_deltas": rows,
        "mean_abs_delta": None if before.get("mean_abs") is None or after.get("mean_abs") is None else float(after["mean_abs"] - before["mean_abs"]),
        "worst_zone_mean_abs_delta": None if before.get("worst_zone_mean_abs") is None or after.get("worst_zone_mean_abs") is None else float(after["worst_zone_mean_abs"] - before["worst_zone_mean_abs"]),
    }

def _lms_affine_from_vertical_residuals(
    right_points: np.ndarray,
    left_points: np.ndarray,
    image_shape: tuple[int, int],
) -> tuple[float, float, float, str]:
    """Fit the StereoFine affine parameters by vertical least squares.

    The fitted correction parameters are the same parameters later used by the
    symmetric image warp: vertical centre shift, relative rotation and scale.
    The linearized residual model is intentionally small and stereo-safe:

        right_y' - left_y' ~= (right_y - left_y)
                             + dy
                             + theta * x_mean_centered
                             + log(scale) * y_mean_centered

    We solve for dy/theta/log(scale) so that the squared vertical residual is
    minimized over the y-RANSAC-filtered inlier set.  If the linear fit becomes
    implausible, the analysis fails deliberately instead of falling back to a
    different correction model.
    """
    right_pts = np.asarray(right_points, dtype=np.float64).reshape(-1, 2)
    left_pts = np.asarray(left_points, dtype=np.float64).reshape(-1, 2)
    if len(right_pts) < 8 or len(left_pts) < 8:
        raise RuntimeError("Zu wenige Inlier für LMS-Affine-Schätzung.")

    h, w = image_shape[:2]
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0

    dy_raw = right_pts[:, 1] - left_pts[:, 1]
    x_mean_centered = 0.5 * ((right_pts[:, 0] - cx) + (left_pts[:, 0] - cx))
    y_mean_centered = 0.5 * ((right_pts[:, 1] - cy) + (left_pts[:, 1] - cy))

    # Scale columns so the least-squares solve is well conditioned while the
    # recovered parameters remain in physical units afterwards.
    sx = max(1.0, float(w))
    sy = max(1.0, float(h))
    a = np.column_stack([
        np.ones(len(dy_raw), dtype=np.float64),
        x_mean_centered / sx,
        y_mean_centered / sy,
    ])
    target = -dy_raw.astype(np.float64)

    params_scaled = _weighted_lstsq(a, target, None)
    affine_fit_method = "vertical_lms"

    centre_shift_y = float(params_scaled[0])
    theta_rad = float(params_scaled[1] / sx)
    log_scale = float(params_scaled[2] / sy)

    rotation_deg = float(np.degrees(theta_rad))
    scale = float(np.exp(log_scale))

    # Plausibility guard. Normal stereo corrections are tiny; if the
    # vertical-only LMS fit becomes ill-conditioned, stop the automatic analysis
    # instead of silently switching to another correction model.
    plausible = (
        np.isfinite(centre_shift_y)
        and np.isfinite(rotation_deg)
        and np.isfinite(scale)
        and abs(centre_shift_y) <= 0.25 * max(1.0, float(h))
        and abs(rotation_deg) <= 5.0
        and 0.90 <= scale <= 1.10
    )
    if not plausible:
        raise RuntimeError("LMS-Schätzung ist geometrisch unplausibel; automatische Korrektur abgebrochen.")

    return scale, rotation_deg, centre_shift_y, affine_fit_method

def _affine_from_center_params(
    width: int,
    height: int,
    rotation_deg: float,
    scale: float,
    center_dx: float,
    center_dy: float,
) -> np.ndarray:
    """Build a simple image operation around the image centre.

    This is the same conceptual operation as in an image editor: rotate/scale
    around the centre and move the centre by dx/dy. It is deliberately not a
    fitted OpenCV model.
    """
    cx = (float(width) - 1.0) / 2.0
    cy = (float(height) - 1.0) / 2.0
    theta = np.radians(float(rotation_deg))
    c = np.cos(theta) * float(scale)
    si = np.sin(theta) * float(scale)
    linear = np.array([[c, -si], [si, c]], dtype=np.float64)
    centre = np.array([cx, cy], dtype=np.float64)
    target_centre = centre + np.array([center_dx, center_dy], dtype=np.float64)
    t = target_centre - linear @ centre
    return np.array([[linear[0, 0], linear[0, 1], t[0]], [linear[1, 0], linear[1, 1], t[1]]], dtype=np.float64)

def _correction_without_y_residual(correction: dict | None) -> dict | None:
    if not correction:
        return correction
    stripped = dict(correction)
    payload = dict(stripped.get("y_residual_apply") or {})
    if payload:
        payload["enabled"] = False
        stripped["y_residual_apply"] = payload
    return stripped

def _y_residual_field_from_payload(height: int, width: int, payload: dict | None) -> np.ndarray | None:
    """Evaluate a stored low-order y residual field on an image grid.

    The payload stores full-resolution pixel coefficients.  x/y are normalized
    image coordinates, matching the diagnostic fit.  `disp` terms are refused
    here because a dense disparity/depth map is not available and using such a
    term as a plain image warp would be stereoscopically unsafe.
    """
    if not payload or not bool(payload.get("enabled", False)):
        return None
    terms = list(payload.get("terms") or [])
    if not terms or "disp" in terms:
        return None
    coeff_rows = payload.get("coefficients") or []
    coeff_by_term = {}
    for row in coeff_rows:
        term = row.get("term")
        if term is not None:
            coeff_by_term[str(term)] = float(row.get("coefficient_fullres_px", 0.0))
    if not coeff_by_term:
        return None

    yy, xx = np.indices((height, width), dtype=np.float32)
    cx = (float(width) - 1.0) / 2.0
    cy = (float(height) - 1.0) / 2.0
    x = (xx - cx) / max(1.0, float(width))
    y = (yy - cy) / max(1.0, float(height))
    norm = payload.get("normalization") or {}
    x2_mean = float(norm.get("x2_mean", 0.0) or 0.0)
    y2_mean = float(norm.get("y2_mean", 0.0) or 0.0)

    field = np.zeros((height, width), dtype=np.float32)
    for term in terms:
        coeff = float(coeff_by_term.get(term, 0.0))
        if abs(coeff) <= 1e-12:
            continue
        if term == "constant":
            field += coeff
        elif term == "x":
            field += coeff * x
        elif term == "y":
            field += coeff * y
        elif term == "xy":
            field += coeff * x * y
        elif term == "x2":
            field += coeff * ((x * x) - x2_mean)
        elif term == "y2":
            field += coeff * ((y * y) - y2_mean)

    max_abs = float(payload.get("max_abs_correction_px", 0.0) or 0.0)
    if max_abs > 0:
        field = np.clip(field, -max_abs, max_abs)
    return field.astype(np.float32)

def _warp_pair_symmetric_simple(
    left: np.ndarray,
    right: np.ndarray,
    correction: dict | None,
) -> tuple[np.ndarray, np.ndarray]:
    """Apply the complete symmetric StereoFine geometry with one resample/eye.

    The former development pipeline rendered Affine first and then resampled
    again for Vergence/Trapezoid and Y-Polish. 1.0 composes the corresponding
    inverse coordinate maps analytically and calls ``cv2.remap`` exactly once
    per half-image. This preserves the established geometry while avoiding
    cumulative interpolation loss.
    """
    if not correction:
        return center_crop_to_common_size(left, right)[:2]

    try:
        import cv2
    except Exception:
        return center_crop_to_common_size(left, right)[:2]

    h = min(left.shape[0], right.shape[0])
    w = min(left.shape[1], right.shape[1])
    if h <= 2 or w <= 2:
        return center_crop_to_common_size(left, right)[:2]

    left_base = np.ascontiguousarray(left[:h, :w])
    right_base = np.ascontiguousarray(right[:h, :w])

    rotation = float(correction.get("rotation_deg", 0.0) or 0.0)
    scale = max(1e-6, float(correction.get("scale", 1.0) or 1.0))
    dy = float(correction.get("vertical_shift_px", 0.0) or 0.0)

    vergence_ready = bool(correction.get("vergence_ready", False))
    vergence_v = float(correction.get("vergence_v_px", 0.0) or 0.0) if vergence_ready else 0.0
    vergence_h = float(correction.get("vergence_h_px", 0.0) or 0.0) if vergence_ready else 0.0

    trapez_payload = correction.get("trapez_apply") or {}
    trapez_enabled = bool(trapez_payload.get("enabled", False))
    trapez_params = trapez_payload.get("params") or {}
    trapez_a = float(trapez_params.get("a_projective_x", 0.0) or 0.0) if trapez_enabled else 0.0
    trapez_b = float(trapez_params.get("b_projective_y", 0.0) or 0.0) if trapez_enabled else 0.0

    y_residual_field = _y_residual_field_from_payload(h, w, correction.get("y_residual_apply"))
    has_y_residual = y_residual_field is not None and bool(np.any(np.abs(y_residual_field) > 1e-12))

    # Preserve true identity pixel-for-pixel. Apart from being faster, this is
    # important for already-perfect pairs and for color-transfer negative tests.
    if (
        abs(rotation) <= 1e-12
        and abs(scale - 1.0) <= 1e-12
        and abs(dy) <= 1e-12
        and abs(vergence_v) <= 1e-12
        and abs(vergence_h) <= 1e-12
        and abs(trapez_a) <= 1e-12
        and abs(trapez_b) <= 1e-12
        and not has_y_residual
    ):
        return left_base, right_base

    yy, xx = np.indices((h, w), dtype=np.float32)
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0

    half_scale = scale ** 0.5
    m_left = _affine_from_center_params(w, h, -rotation / 2.0, 1.0 / half_scale, 0.0, -dy / 2.0)
    m_right = _affine_from_center_params(w, h, rotation / 2.0, half_scale, 0.0, dy / 2.0)
    inv_left = cv2.invertAffineTransform(m_left).astype(np.float64)
    inv_right = cv2.invertAffineTransform(m_right).astype(np.float64)

    def composed_map(side: str) -> tuple[np.ndarray, np.ndarray]:
        # Start at the final destination grid and walk backwards through the
        # exact order of the old sequential image operations:
        # Y-Polish -> Trapezoid -> Vergence -> Affine -> master.
        qx = xx.astype(np.float64)
        qy = yy.astype(np.float64)

        if has_y_residual:
            half_y = 0.5 * y_residual_field.astype(np.float64)
            if side == "left":
                qy = qy - half_y
            else:
                qy = qy + half_y

        if abs(trapez_a) > 1e-12 or abs(trapez_b) > 1e-12:
            u = qx - cx
            v = qy - cy
            xn = u / max(1.0, float(w))
            yn = v / max(1.0, float(h))
            side_strength = -0.5 if side == "left" else +0.5
            projective_q = side_strength * (trapez_a * xn + trapez_b * yn)
            denom = 1.0 - projective_q
            denom = np.where(
                np.abs(denom) < 1e-6,
                np.where(denom < 0.0, -1e-6, 1e-6),
                denom,
            )
            qx = cx + u / denom
            qy = cy + v / denom

        if abs(vergence_v) > 1e-12 or abs(vergence_h) > 1e-12:
            x_norm = (qx - cx) / max(1.0, float(w))
            y_norm = (qy - cy) / max(1.0, float(h))
            half_v = 0.5 * vergence_v * x_norm
            half_h = 0.5 * vergence_h * y_norm
            if side == "left":
                qx = qx - half_h
                qy = qy - half_v
            else:
                qx = qx + half_h
                qy = qy + half_v

        inv = inv_left if side == "left" else inv_right
        src_x = inv[0, 0] * qx + inv[0, 1] * qy + inv[0, 2]
        src_y = inv[1, 0] * qx + inv[1, 1] * qy + inv[1, 2]
        return src_x.astype(np.float32), src_y.astype(np.float32)

    left_map_x, left_map_y = composed_map("left")
    right_map_x, right_map_y = composed_map("right")

    # A single high-quality interpolation per master image.
    left_warped = cv2.remap(
        left_base,
        left_map_x,
        left_map_y,
        interpolation=cv2.INTER_LANCZOS4,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(0, 0, 0),
    )
    right_warped = cv2.remap(
        right_base,
        right_map_x,
        right_map_y,
        interpolation=cv2.INTER_LANCZOS4,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(0, 0, 0),
    )

    # Determine the common fully valid area directly from the composed master
    # maps. This replaces the repeatedly resampled binary masks of the old path.
    left_valid = (
        np.isfinite(left_map_x)
        & np.isfinite(left_map_y)
        & (left_map_x >= -0.5)
        & (left_map_x < float(w) - 0.5)
        & (left_map_y >= -0.5)
        & (left_map_y < float(h) - 0.5)
    )
    right_valid = (
        np.isfinite(right_map_x)
        & np.isfinite(right_map_y)
        & (right_map_x >= -0.5)
        & (right_map_x < float(w) - 0.5)
        & (right_map_y >= -0.5)
        & (right_map_y < float(h) - 0.5)
    )
    crop_box = _largest_all_valid_rectangle(left_valid & right_valid)
    if crop_box is None:
        return center_crop_to_common_size(left_warped, right_warped)[:2]

    x0, y0, x1, y1 = crop_box
    return (
        np.ascontiguousarray(left_warped[y0:y1, x0:x1]),
        np.ascontiguousarray(right_warped[y0:y1, x0:x1]),
    )

def warp_pair_symmetric(
    left: np.ndarray,
    right: np.ndarray,
    correction: dict | None,
) -> tuple[np.ndarray, np.ndarray]:
    """Public rendering entry point for the validated StereoFine correction payload."""
    return _warp_pair_symmetric_simple(left, right, correction)


def _transform_points_by_center_params(points: np.ndarray, image_shape: tuple[int, int], rotation_deg: float, scale: float, center_dx: float, center_dy: float) -> np.ndarray:
    h, w = image_shape[:2]
    matrix = _affine_from_center_params(w, h, rotation_deg, scale, center_dx, center_dy)
    return _transform_points(matrix, np.asarray(points, dtype=np.float64).reshape(-1, 2))

def _quadrant_counts(points: np.ndarray, image_shape: tuple[int, int]) -> list[int]:
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    h, w = image_shape[:2]
    cx = w / 2.0
    cy = h / 2.0
    return [
        int(np.sum((pts[:, 0] < cx) & (pts[:, 1] < cy))),
        int(np.sum((pts[:, 0] >= cx) & (pts[:, 1] < cy))),
        int(np.sum((pts[:, 0] < cx) & (pts[:, 1] >= cy))),
        int(np.sum((pts[:, 0] >= cx) & (pts[:, 1] >= cy))),
    ]

def _fit_vergence_from_affine_residuals(
    left_points_after_affine: np.ndarray,
    right_points_after_affine: np.ndarray,
    image_shape: tuple[int, int],
) -> tuple[float, float]:
    """Estimate Vergence V/H with a least-squares residual fit.

    StereoFine keeps this model deliberately limited:
    - Affine (height/rotation/scale) is estimated from y-RANSAC-filtered inliers.
    - Vergence V/H is only measured from the affine residual field.

    In this zone basis, the slope fit can optionally use the same 3x3 zone
    balancing as affine LMS. That tests whether a more evenly distributed point
    pattern supports the first-order V/H terms better than raw point density.
    """
    left_pts = np.asarray(left_points_after_affine, dtype=np.float64).reshape(-1, 2)
    right_pts = np.asarray(right_points_after_affine, dtype=np.float64).reshape(-1, 2)
    if len(left_pts) < 4 or len(right_pts) < 4:
        return 0.0, 0.0

    h, w = image_shape[:2]
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0

    residual_x = right_pts[:, 0] - left_pts[:, 0]
    residual_y = right_pts[:, 1] - left_pts[:, 1]

    rx = residual_x - float(np.median(residual_x))
    ry = residual_y - float(np.median(residual_y))

    x_norm = (left_pts[:, 0] - cx) / max(1.0, float(w))
    y_norm = (left_pts[:, 1] - cy) / max(1.0, float(h))

    def lms_slope(axis: np.ndarray, values: np.ndarray) -> float:
        mask = np.isfinite(axis) & np.isfinite(values) & (np.abs(axis) > 1e-6)
        if int(mask.sum()) < 4:
            return 0.0
        a = axis[mask].astype(np.float64)
        v = values[mask].astype(np.float64)
        denom = float(np.dot(a, a))
        if denom <= 1e-12:
            return 0.0
        return float(np.dot(a, v) / denom)

    vergence_v_px = lms_slope(x_norm, ry)
    vergence_h_px = lms_slope(y_norm, rx)
    return vergence_v_px, vergence_h_px

def _pipeline_mean_points(left_points: np.ndarray, right_points: np.ndarray) -> np.ndarray:
    left_pts = np.asarray(left_points, dtype=np.float64).reshape(-1, 2)
    right_pts = np.asarray(right_points, dtype=np.float64).reshape(-1, 2)
    n = min(len(left_pts), len(right_pts))
    if n == 0:
        return np.zeros((0, 2), dtype=np.float64)
    return 0.5 * (left_pts[:n] + right_pts[:n])

def _pipeline_vertical_residual_signed(left_points: np.ndarray, right_points: np.ndarray) -> np.ndarray:
    left_pts = np.asarray(left_points, dtype=np.float64).reshape(-1, 2)
    right_pts = np.asarray(right_points, dtype=np.float64).reshape(-1, 2)
    n = min(len(left_pts), len(right_pts))
    if n == 0:
        return np.zeros((0,), dtype=np.float64)
    return right_pts[:n, 1] - left_pts[:n, 1]

def _pipeline_holdout_mask(points: np.ndarray, stride: int = TRAPEZ_HOLDOUT_STRIDE) -> tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
    n = len(pts)
    if n == 0:
        return np.zeros((0,), dtype=np.int64), np.zeros((0,), dtype=np.int64)
    stride = max(3, int(stride))
    order = np.lexsort((pts[:, 0], pts[:, 1]))
    holdout_mask = np.zeros((n,), dtype=bool)
    holdout_mask[order[::stride]] = True
    if int(np.sum(holdout_mask)) >= n - 4:
        holdout_mask[:] = False
        holdout_mask[::stride] = True
    train_mask = ~holdout_mask
    if int(np.sum(train_mask)) < 8:
        train_mask[:] = True
        holdout_mask[:] = False
    return np.where(train_mask)[0], np.where(holdout_mask)[0]

def _pipeline_design_quality(features: np.ndarray, weights: np.ndarray | None = None) -> dict:
    """Numerical support check for the 2-parameter trapez fit.

    Pipeline v4 deliberately removes the hard four-quadrant gate.  Instead we
    check whether the actual design matrix is solvable: enough rows, finite
    values, rank 2 and a sane condition number.  This is a numerical stability
    test, not a manually guessed image-area rule.
    """
    a = np.asarray(features, dtype=np.float64)
    if a.ndim != 2 or a.shape[1] == 0:
        return {
            "rows": 0,
            "cols": 0,
            "rank": 0,
            "condition": None,
            "supported": False,
            "reason": "empty_design_matrix",
        }

    mask = np.all(np.isfinite(a), axis=1)
    a = a[mask]
    if weights is not None:
        w = np.asarray(weights, dtype=np.float64).reshape(-1)
        w = w[mask] if len(w) == len(mask) else np.ones((len(a),), dtype=np.float64)
        if len(w) == len(a) and np.all(np.isfinite(w)) and float(np.sum(w)) > 1e-12:
            a = a * np.sqrt(np.clip(w, 0.0, None))[:, None]

    rows, cols = a.shape
    if rows < max(cols + 4, TRAPEZ_MIN_TRAIN_POINTS):
        return {
            "rows": int(rows),
            "cols": int(cols),
            "rank": 0,
            "condition": None,
            "supported": False,
            "reason": "too_few_training_points",
        }

    try:
        singular_values = np.linalg.svd(a, compute_uv=False)
    except Exception:
        return {
            "rows": int(rows),
            "cols": int(cols),
            "rank": 0,
            "condition": None,
            "supported": False,
            "reason": "svd_failed",
        }

    if len(singular_values) == 0 or not np.all(np.isfinite(singular_values)):
        return {
            "rows": int(rows),
            "cols": int(cols),
            "rank": 0,
            "condition": None,
            "supported": False,
            "reason": "nonfinite_singular_values",
        }

    s0 = float(singular_values[0])
    smin = float(singular_values[-1])
    tol = max(a.shape) * np.finfo(np.float64).eps * max(s0, 1.0)
    rank = int(np.sum(singular_values > tol))
    condition = None if smin <= tol else float(s0 / smin)
    supported = bool(rank >= cols and condition is not None and condition <= TRAPEZ_MAX_DESIGN_CONDITION)
    reason = "ok"
    if rank < cols:
        reason = "rank_deficient_design"
    elif condition is None:
        reason = "singular_design"
    elif condition > TRAPEZ_MAX_DESIGN_CONDITION:
        reason = "ill_conditioned_design"

    return {
        "rows": int(rows),
        "cols": int(cols),
        "rank": int(rank),
        "condition": condition,
        "singular_values": [float(v) for v in singular_values.tolist()],
        "supported": bool(supported),
        "reason": reason,
        "max_condition": float(TRAPEZ_MAX_DESIGN_CONDITION),
    }

def _pipeline_ridge_lstsq(
    features: np.ndarray,
    target: np.ndarray,
    ridge: float = 1e-8,
    weights: np.ndarray | None = None,
) -> np.ndarray:
    a = np.asarray(features, dtype=np.float64)
    y = np.asarray(target, dtype=np.float64)
    mask = np.all(np.isfinite(a), axis=1) & np.isfinite(y)
    a = a[mask]
    y = y[mask]
    w = None
    if weights is not None:
        weights_arr = np.asarray(weights, dtype=np.float64).reshape(-1)
        if len(weights_arr) == len(mask):
            w = weights_arr[mask]

    if len(y) == 0 or a.shape[0] < a.shape[1]:
        raise RuntimeError("Zu wenige gültige Punkte für Trapez-Least-Squares-Fit.")

    if w is not None and len(w) == len(y) and np.all(np.isfinite(w)) and float(np.sum(w)) > 1e-12:
        sw = np.sqrt(np.clip(w, 0.0, None))
        a = a * sw[:, None]
        y = y * sw

    ata = a.T @ a
    aty = a.T @ y
    reg = np.eye(a.shape[1], dtype=np.float64) * float(ridge)
    return np.linalg.solve(ata + reg, aty)

def fit_pipeline_trapez_projective_model(
    left_points_after_base: np.ndarray,
    right_points_after_base: np.ndarray,
    image_shape: tuple[int, int],
    train_idx: np.ndarray,
) -> dict:
    left_train = np.asarray(left_points_after_base, dtype=np.float64).reshape(-1, 2)[train_idx]
    right_train = np.asarray(right_points_after_base, dtype=np.float64).reshape(-1, 2)[train_idx]
    mean_train = _pipeline_mean_points(left_train, right_train)
    residual = _pipeline_vertical_residual_signed(left_train, right_train)
    h, w = image_shape[:2]
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0
    u = mean_train[:, 0] - cx
    v = mean_train[:, 1] - cy
    x_norm = u / max(1.0, float(w))
    y_norm = v / max(1.0, float(h))
    # Begrenzter projektiver Trapez-/Kippterm: x/y werden gemeinsam über einen
    # zentrischen Nenner verändert, aber Fit-Ziel bleibt ausschließlich der
    # vertikale Restfehler. Horizontale Disparität wird nicht minimiert.
    features = np.column_stack([v * x_norm, v * y_norm])
    weights = _zone_capped_weights(
        mean_train,
        image_shape,
        ZONE_DIAGNOSTICS_GRID,
        TRAPEZ_ZONE_SOFT_CAP_PER_ZONE,
    )
    design_quality = _pipeline_design_quality(features, weights=weights)
    if not bool(design_quality.get("supported", False)):
        raise RuntimeError(f"Trapez-Fit nicht stabil genug: {design_quality.get('reason')}")
    coeff = _pipeline_ridge_lstsq(features, residual, ridge=1e-6, weights=weights)
    return {
        "a_projective_x": float(coeff[0]),
        "b_projective_y": float(coeff[1]),
        "fit_method": "centered_projective_2param_vertical_lms_zone_capped",
        "target": "vertical_residual_only",
        "horizontal_disparity_target": "not_minimized",
        "design_quality": design_quality,
        "zone_soft_cap_per_zone": int(TRAPEZ_ZONE_SOFT_CAP_PER_ZONE),
    }

def apply_pipeline_trapez_projective_to_points(
    left_points: np.ndarray,
    right_points: np.ndarray,
    image_shape: tuple[int, int],
    params: dict,
) -> tuple[np.ndarray, np.ndarray]:
    a = float(params.get("a_projective_x", 0.0) or 0.0)
    b = float(params.get("b_projective_y", 0.0) or 0.0)

    def transform(points: np.ndarray, side_strength: float) -> np.ndarray:
        pts = np.asarray(points, dtype=np.float64).reshape(-1, 2)
        h, w = image_shape[:2]
        cx = (float(w) - 1.0) / 2.0
        cy = (float(h) - 1.0) / 2.0
        u = pts[:, 0] - cx
        v = pts[:, 1] - cy
        x_norm = u / max(1.0, float(w))
        y_norm = v / max(1.0, float(h))
        denom = 1.0 + side_strength * (a * x_norm + b * y_norm)
        denom[np.abs(denom) < 1e-9] = 1e-9
        out = np.empty_like(pts, dtype=np.float64)
        out[:, 0] = cx + u / denom
        out[:, 1] = cy + v / denom
        return out

    return transform(left_points, -0.5), transform(right_points, +0.5)

def pipeline_trapez_plausibility(image_shape: tuple[int, int], params: dict) -> dict:
    a = float(params.get("a_projective_x", 0.0) or 0.0)
    b = float(params.get("b_projective_y", 0.0) or 0.0)
    h, w = image_shape[:2]
    corners = np.array(
        [[0.0, 0.0], [float(w - 1), 0.0], [float(w - 1), float(h - 1)], [0.0, float(h - 1)]],
        dtype=np.float64,
    )
    left_c, right_c = apply_pipeline_trapez_projective_to_points(corners, corners, image_shape, params)
    left_shift = np.linalg.norm(left_c - corners, axis=1)
    right_shift = np.linalg.norm(right_c - corners, axis=1)
    max_corner_shift_px = float(max(np.max(left_shift), np.max(right_shift)))
    max_corner_shift_permille = max_corner_shift_px / max(1.0, float(w)) * 1000.0

    def edge_lengths(pts: np.ndarray) -> np.ndarray:
        return np.array([
            np.linalg.norm(pts[1] - pts[0]),
            np.linalg.norm(pts[2] - pts[1]),
            np.linalg.norm(pts[2] - pts[3]),
            np.linalg.norm(pts[3] - pts[0]),
        ], dtype=np.float64)

    base_lengths = edge_lengths(corners)
    left_lengths = edge_lengths(left_c)
    right_lengths = edge_lengths(right_c)
    stretch_left = np.abs(left_lengths / np.maximum(base_lengths, 1e-12) - 1.0) * 100.0
    stretch_right = np.abs(right_lengths / np.maximum(base_lengths, 1e-12) - 1.0) * 100.0
    max_edge_stretch_percent = float(max(np.max(stretch_left), np.max(stretch_right)))

    sample = np.vstack([corners, np.array([[(float(w - 1)) / 2.0, (float(h - 1)) / 2.0]], dtype=np.float64)])
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0
    x_norm = (sample[:, 0] - cx) / max(1.0, float(w))
    y_norm = (sample[:, 1] - cy) / max(1.0, float(h))
    denom_left = 1.0 - 0.5 * (a * x_norm + b * y_norm)
    denom_right = 1.0 + 0.5 * (a * x_norm + b * y_norm)
    min_denom = float(min(np.min(denom_left), np.min(denom_right)))
    relative_y_delta_corners = right_c[:, 1] - left_c[:, 1]
    max_relative_y_correction_px_analysis = float(np.max(np.abs(relative_y_delta_corners)))

    warning_checks = {
        "param_abs_warning_ok": abs(a) <= TRAPEZ_WARNING_MAX_PARAM_ABS and abs(b) <= TRAPEZ_WARNING_MAX_PARAM_ABS,
        "denominator_warning_ok": min_denom >= TRAPEZ_WARNING_MIN_DENOMINATOR,
        "corner_shift_warning_ok": max_corner_shift_permille <= TRAPEZ_WARNING_MAX_CORNER_SHIFT_PERMILLE,
        "edge_stretch_warning_ok": max_edge_stretch_percent <= TRAPEZ_WARNING_MAX_EDGE_STRETCH_PERCENT,
    }
    hard_checks = {
        "finite_ok": bool(np.isfinite(a) and np.isfinite(b) and np.isfinite(min_denom)),
        "param_abs_hard_ok": abs(a) <= TRAPEZ_HARD_MAX_PARAM_ABS and abs(b) <= TRAPEZ_HARD_MAX_PARAM_ABS,
        "denominator_hard_ok": min_denom >= TRAPEZ_HARD_MIN_DENOMINATOR,
    }
    return {
        "plausible": bool(all(hard_checks.values())),
        "warning": not bool(all(warning_checks.values())),
        "checks": warning_checks,
        "hard_checks": hard_checks,
        "a_projective_x": a,
        "b_projective_y": b,
        "max_corner_shift_px_analysis": max_corner_shift_px,
        "max_corner_shift_permille_width": max_corner_shift_permille,
        "max_edge_stretch_percent": max_edge_stretch_percent,
        "max_relative_y_correction_px_analysis": max_relative_y_correction_px_analysis,
        "min_half_denominator": min_denom,
        "note": "Warnwerte sind Diagnose; harte Checks nur Notbremse gegen numerisch absurde Projektivterme.",
    }

def _pipeline_y_payload_from_candidate(candidate: dict, enabled: bool, source: str) -> dict:
    coefficients = []
    for row in candidate.get("coefficients", []) or []:
        coefficients.append({
            "term": row.get("term"),
            "coefficient_fullres_px": float(row.get("coefficient_fullres_px_approx", 0.0)),
        })
    return {
        "enabled": bool(enabled),
        "model_name": Y_RESIDUAL_APPLY_MODEL_NAME,
        "terms": list(candidate.get("terms", [])),
        "coefficients": coefficients,
        "normalization": candidate.get("normalization", {}),
        "max_abs_correction_px": float(candidate.get("max_abs_model_fullres_px", 0.0) or 0.0),
        "source": source,
        "note": "Symmetric low-order vertical residual field; no horizontal disparity optimization.",
    }

def _pipeline_vertical_summary_from_candidate(candidate: dict | None, fallback_summary: dict) -> dict:
    if not candidate:
        return fallback_summary
    vertical = candidate.get("vertical") or {}
    return vertical or fallback_summary

def _holdout_summary_is_better(baseline: dict | None, corrected: dict | None) -> bool:
    """Threshold-free Pareto gate for adding geometric complexity.

    The candidate must strictly improve holdout mean absolute vertical error and
    may not worsen median, p90, p95 or maximum error.  This rejects tiny fits
    that merely trade one part of the image against another, without inventing a
    new pixel threshold.
    """
    if not baseline or not corrected:
        return False
    metrics = ("mean_abs", "median_abs", "p90_abs", "p95_abs", "max_abs")
    try:
        base = {key: float(baseline[key]) for key in metrics}
        cand = {key: float(corrected[key]) for key in metrics}
    except (KeyError, TypeError, ValueError):
        return False
    if not np.isfinite(list(base.values()) + list(cand.values())).all():
        return False
    return bool(
        cand["mean_abs"] < base["mean_abs"]
        and all(cand[key] <= base[key] for key in ("median_abs", "p90_abs", "p95_abs", "max_abs"))
    )


def _holdout_model_is_better(candidate: dict | None) -> bool:
    """Conservative auto-enable gate for a fitted residual model."""
    if not candidate or not bool(candidate.get("ready", False)):
        return False
    if candidate.get("eval_mode") != "spatial_holdout":
        return False
    return _holdout_summary_is_better(
        candidate.get("baseline_holdout") or {},
        candidate.get("vertical_holdout") or {},
    )


def analyze_pair_features(
    left: np.ndarray,
    right: np.ndarray,
    method: str,
    max_width: int,
) -> dict:
    """Vergence model basis: keep affine output, compare V/H candidates.

    This basis deliberately does not promote a new correction model.  The
    actual applied correction remains the stable unweighted Affine-LMS result.
    The sidecar stores the measured residual fields for:
      - Affine only
      - Affine + V only (vertical residual slope over x)
      - Affine + H only (current horizontal vergence term; vertical residual is
        expected to stay unchanged in this point model)
      - Affine + V+H

    The purpose is to evaluate the current Vergence model over multiple data
    sets without adding UI controls or changing the stable basis.
    """
    try:
        import cv2
    except Exception as exc:
        raise RuntimeError("OpenCV ist nicht installiert oder konnte nicht geladen werden.") from exc

    left_gray, right_gray, analysis_scale = resize_pair_for_analysis(left, right, max_width)
    h, w = left_gray.shape[:2]

    method_upper = method.upper()
    if method_upper == "AKAZE":
        detector = cv2.AKAZE_create()
        norm_type = cv2.NORM_HAMMING
    elif method_upper == "SIFT":
        if not hasattr(cv2, "SIFT_create"):
            raise RuntimeError("SIFT ist in dieser OpenCV-Version nicht verfügbar.")
        detector = cv2.SIFT_create()
        norm_type = cv2.NORM_L2
    else:
        raise RuntimeError(f"Unbekanntes Analyseverfahren: {method}")

    kp_left, desc_left = detector.detectAndCompute(left_gray, None)
    kp_right, desc_right = detector.detectAndCompute(right_gray, None)

    if desc_left is None or desc_right is None or len(kp_left) < 4 or len(kp_right) < 4:
        raise RuntimeError("Zu wenige Merkmale für eine zuverlässige Analyse gefunden.")

    matcher = cv2.BFMatcher(norm_type, crossCheck=False)
    raw_matches = matcher.knnMatch(desc_right, desc_left, k=2)

    good_matches = []
    for pair in raw_matches:
        if len(pair) != 2:
            continue
        m, n = pair
        if m.distance < 0.75 * n.distance:
            good_matches.append(m)

    if len(good_matches) < 8:
        raise RuntimeError("Zu wenige stabile Übereinstimmungen nach dem Matching gefunden.")

    pts_right = np.float32([kp_right[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
    pts_left = np.float32([kp_left[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)

    # y-RANSAC is the stereoscopic first-stage filter: it scores only vertical
    # plausibility and deliberately ignores horizontal disparity, because
    # horizontal disparity is scene depth, not an alignment error.
    raw_right_points_all = pts_right.reshape(-1, 2).astype(np.float64)
    raw_left_points_all = pts_left.reshape(-1, 2).astype(np.float64)
    raw_anchor_points_all = 0.5 * (raw_right_points_all + raw_left_points_all)

    y_filter_result = _fit_vertical_ransac_filter(
        raw_anchor_points_all,
        raw_right_points_all,
        raw_left_points_all,
        left_gray.shape,
        threshold_analysis_px=3.0,
    )
    mask = np.asarray(y_filter_result.get("mask", []), dtype=bool).reshape(-1)
    if len(mask) != len(raw_right_points_all):
        raise RuntimeError("y-RANSAC konnte keine stabile Inlier-Gruppe bestimmen.")
    if int(mask.sum()) < 8:
        raise RuntimeError("Zu wenige Inlier für eine stabile Analyse gefunden (y-RANSAC).")

    right_in = raw_right_points_all[mask]
    left_in = raw_left_points_all[mask]

    scale, rotation_deg, centre_shift_y_analysis, affine_fit_method = _lms_affine_from_vertical_residuals(
        right_in,
        left_in,
        left_gray.shape,
    )
    vertical_shift_px = centre_shift_y_analysis / analysis_scale

    # Predict residual after our actual symmetric affine correction, not after
    # any discarded 2D reprojection matrix.
    half_scale = max(1e-6, scale) ** 0.5
    left_mid = _transform_points_by_center_params(
        left_in,
        left_gray.shape,
        -rotation_deg / 2.0,
        1.0 / half_scale,
        0.0,
        -centre_shift_y_analysis / 2.0,
    )
    right_mid = _transform_points_by_center_params(
        right_in,
        right_gray.shape,
        rotation_deg / 2.0,
        half_scale,
        0.0,
        centre_shift_y_analysis / 2.0,
    )

    pre_affine_vertical_signed = right_in[:, 1] - left_in[:, 1]
    pre_affine_anchor_points = 0.5 * (right_in + left_in)

    affine_vertical_signed = right_mid[:, 1] - left_mid[:, 1]
    affine_vertical_abs = np.abs(affine_vertical_signed) / analysis_scale
    horizontal_signed = right_mid[:, 0] - left_mid[:, 0]
    horizontal_abs = np.abs(horizontal_signed) / analysis_scale

    coverage_percent = _point_coverage_percent(left_in, left_gray.shape)
    # Pipeline v4: keine Quadrantenbedingung mehr.  Die alte einfache V/H-
    # Diagnose bleibt nur als Messwert erhalten; die eigentliche Trapez-/
    # Vergence-Stufe wird weiter unten über Gesamt-Inlier, Trainingspunkte,
    # Design-Matrix-Stabilität und harte numerische Plausibilität beurteilt.
    vergence_candidate_ready = int(mask.sum()) >= TRAPEZ_MIN_TOTAL_INLIERS

    vergence_v_analysis, vergence_h_analysis = _fit_vergence_from_affine_residuals(
        left_mid,
        right_mid,
        left_gray.shape,
    )
    vergence_v_candidate_px = vergence_v_analysis / analysis_scale
    vergence_h_candidate_px = vergence_h_analysis / analysis_scale

    cx = (w - 1.0) / 2.0
    cy = (h - 1.0) / 2.0
    x_norm = (left_mid[:, 0] - cx) / max(1.0, float(w))
    y_norm = (left_mid[:, 1] - cy) / max(1.0, float(h))

    # Current application semantics:
    #   V changes y by a term over x and therefore changes vertical residuals.
    #   H changes x by a term over y and therefore does not change the measured
    #   vertical point residual in this simplified point-field simulation.
    v_only_vertical_signed = affine_vertical_signed - vergence_v_analysis * x_norm
    h_only_vertical_signed = affine_vertical_signed.copy()
    vh_vertical_signed = v_only_vertical_signed.copy()

    # H is still stored as a diagnostic of the y-dependent horizontal disparity
    # trend.  Depth itself remains horizontal disparity, so this is not used as
    # a quality score for stereo alignment; it is just a model sanity check.
    horizontal_centered = horizontal_signed - float(np.median(horizontal_signed))
    h_corrected_horizontal_signed = horizontal_centered - vergence_h_analysis * y_norm

    def residual_summary(signed_values_analysis: np.ndarray) -> dict:
        signed_px = np.asarray(signed_values_analysis, dtype=np.float64).reshape(-1) / max(1e-12, analysis_scale)
        if len(signed_px) == 0:
            return {
                "mean_signed": None,
                "mean_abs": None,
                "median_abs": None,
                "p90_abs": None,
                "p95_abs": None,
                "max_abs": None,
            }
        abs_px = np.abs(signed_px)
        return {
            "mean_signed": float(np.mean(signed_px)),
            "mean_abs": float(np.mean(abs_px)),
            "median_abs": float(np.median(abs_px)),
            "p90_abs": float(np.percentile(abs_px, 90)),
            "p95_abs": float(np.percentile(abs_px, 95)),
            "max_abs": float(np.max(abs_px)),
        }

    pre_affine_zone3x3 = _vertical_residual_zone_stats(
        pre_affine_anchor_points,
        pre_affine_vertical_signed,
        left_gray.shape,
        analysis_scale,
        ZONE_DIAGNOSTICS_GRID,
    )
    affine_zone3x3 = _vertical_residual_zone_stats(
        left_mid,
        affine_vertical_signed,
        left_gray.shape,
        analysis_scale,
        ZONE_DIAGNOSTICS_GRID,
    )
    v_only_zone3x3 = _vertical_residual_zone_stats(
        left_mid,
        v_only_vertical_signed,
        left_gray.shape,
        analysis_scale,
        ZONE_DIAGNOSTICS_GRID,
    )
    h_only_zone3x3 = _vertical_residual_zone_stats(
        left_mid,
        h_only_vertical_signed,
        left_gray.shape,
        analysis_scale,
        ZONE_DIAGNOSTICS_GRID,
    )
    vh_zone3x3 = _vertical_residual_zone_stats(
        left_mid,
        vh_vertical_signed,
        left_gray.shape,
        analysis_scale,
        ZONE_DIAGNOSTICS_GRID,
    )

    y_residual_candidates = {}
    for y_model_name, y_model_terms in Y_RESIDUAL_MODEL_SPECS.items():
        candidate = _fit_y_residual_candidate(
            y_model_name,
            y_model_terms,
            left_mid,
            right_mid,
            affine_vertical_signed,
            left_gray.shape,
            analysis_scale,
        )
        candidate["vs_affine"] = _zone_improvement_stats(affine_zone3x3, candidate["zone3x3"])
        base_holdout = candidate.get("baseline_holdout") or {}
        cand_holdout = candidate.get("vertical_holdout") or {}
        if base_holdout.get("mean_abs") is not None and cand_holdout.get("mean_abs") is not None:
            candidate["vs_affine_holdout_mean_abs_delta"] = float(cand_holdout["mean_abs"] - base_holdout["mean_abs"])
        y_residual_candidates[y_model_name] = candidate

    candidate_summaries = {
        "affine": {
            "vertical": residual_summary(affine_vertical_signed),
            "horizontal_centered": residual_summary(horizontal_centered),
        },
        "v_only": {
            "vertical": residual_summary(v_only_vertical_signed),
            "params": {"vergence_v_px": float(vergence_v_candidate_px), "vergence_h_px": 0.0},
        },
        "h_only": {
            "vertical": residual_summary(h_only_vertical_signed),
            "horizontal_centered_after_h": residual_summary(h_corrected_horizontal_signed),
            "params": {"vergence_v_px": 0.0, "vergence_h_px": float(vergence_h_candidate_px)},
            "note": "H term shifts x over y; vertical point residual is unchanged by design.",
        },
        "v_plus_h": {
            "vertical": residual_summary(vh_vertical_signed),
            "horizontal_centered_after_h": residual_summary(h_corrected_horizontal_signed),
            "params": {"vergence_v_px": float(vergence_v_candidate_px), "vergence_h_px": float(vergence_h_candidate_px)},
        },
    }
    for y_model_name, y_candidate in y_residual_candidates.items():
        candidate_summaries[y_model_name] = {
            "vertical": y_candidate.get("vertical"),
            "vertical_holdout": y_candidate.get("vertical_holdout"),
            "baseline_holdout": y_candidate.get("baseline_holdout"),
            "vs_affine_holdout_mean_abs_delta": y_candidate.get("vs_affine_holdout_mean_abs_delta"),
            "ready": y_candidate.get("ready"),
            "terms": y_candidate.get("terms"),
            "model_summary": y_candidate.get("model_summary"),
            "note": "Low-order y-residual model after Affine-LMS; y_quad is visually applied when ready in this apply basis.",
        }

    zone3x3_diagnostics = {
        "basis": ZONE_PROBE_ID,
        "grid": ZONE_DIAGNOSTICS_GRID,
        "pre_affine": pre_affine_zone3x3,
        "affine": affine_zone3x3,
        "y_residual_models": {name: cand.get("zone3x3") for name, cand in y_residual_candidates.items()},
        "y_residual_models_holdout": {name: cand.get("zone3x3_holdout") for name, cand in y_residual_candidates.items()},
        "y_residual_models_vs_affine": {name: cand.get("vs_affine") for name, cand in y_residual_candidates.items()},
        "v_only": v_only_zone3x3,
        "h_only": h_only_zone3x3,
        "v_plus_h": vh_zone3x3,
        "v_only_vs_affine": _zone_improvement_stats(affine_zone3x3, v_only_zone3x3),
        "h_only_vs_affine": _zone_improvement_stats(affine_zone3x3, h_only_zone3x3),
        "v_plus_h_vs_affine": _zone_improvement_stats(affine_zone3x3, vh_zone3x3),
    }

    y_residual_apply_candidate = y_residual_candidates.get(Y_RESIDUAL_APPLY_MODEL_NAME) or {}
    y_residual_apply_ready = _holdout_model_is_better(y_residual_apply_candidate)
    y_residual_apply_candidate["auto_enable_holdout_gate"] = bool(y_residual_apply_ready)
    y_residual_apply_summary = y_residual_apply_candidate.get("vertical") if y_residual_apply_ready else residual_summary(affine_vertical_signed)
    y_residual_apply_coefficients = []
    for row in y_residual_apply_candidate.get("coefficients", []) or []:
        y_residual_apply_coefficients.append({
            "term": row.get("term"),
            "coefficient_fullres_px": float(row.get("coefficient_fullres_px_approx", 0.0)),
        })
    y_residual_apply_payload = {
        "enabled": bool(y_residual_apply_ready),
        "model_name": Y_RESIDUAL_APPLY_MODEL_NAME,
        "terms": list(y_residual_apply_candidate.get("terms", [])),
        "coefficients": y_residual_apply_coefficients,
        "normalization": y_residual_apply_candidate.get("normalization", {}),
        "max_abs_correction_px": float(y_residual_apply_candidate.get("max_abs_model_fullres_px", 0.0) or 0.0),
        "source": "y_residual_apply_basis_v1",
        "note": "Applied symmetrically as a low-order vertical residual field after Affine-LMS; no horizontal disparity optimization.",
    }


    # Pipeline v4: Trapez/Vergence wird nach Affine-LMS geschätzt. Die harte
    # Quadrantenlogik ist vollständig aus der Aktivierung entfernt. Stattdessen
    # gelten nur: genug robuste Inlier, genug Trainingspunkte, numerisch stabile
    # 2-Parameter-Schätzung und harte Plausibilitäts-Notbremsen.  3x3 bleibt
    # Audit-/Gewichtungslogik, aber kein Mesh und kein Blocker.
    y_residual_apply_payload_affine = dict(y_residual_apply_payload)
    train_idx, holdout_idx = _pipeline_holdout_mask(left_mid, TRAPEZ_HOLDOUT_STRIDE)
    trapez_zone_counts = _grid_zone_counts(left_mid, left_gray.shape, ZONE_DIAGNOSTICS_GRID)
    trapez_support = {
        "rule": "no_quadrant_gate_total_points_train_points_design_stability",
        "total_inliers": int(mask.sum()),
        "min_total_inliers": int(TRAPEZ_MIN_TOTAL_INLIERS),
        "train_points": int(len(train_idx)),
        "min_train_points": int(TRAPEZ_MIN_TRAIN_POINTS),
        "holdout_points": int(len(holdout_idx)),
        "coverage_percent_bbox": float(coverage_percent),
        "grid": int(ZONE_DIAGNOSTICS_GRID),
        "zone_counts": [int(c) for c in trapez_zone_counts],
        "occupied_zones": int(sum(1 for c in trapez_zone_counts if int(c) > 0)),
        "zone_soft_cap_per_zone": int(TRAPEZ_ZONE_SOFT_CAP_PER_ZONE),
        "note": "3x3 dient nur Audit/Gewichtung; keine harte Quadrantenbedingung.",
    }
    trapez_supported = (
        int(mask.sum()) >= TRAPEZ_MIN_TOTAL_INLIERS
        and int(len(train_idx)) >= TRAPEZ_MIN_TRAIN_POINTS
    )
    trapez_support["supported_before_fit"] = bool(trapez_supported)
    trapez_support["reason_before_fit"] = (
        "ok" if trapez_supported else "insufficient_total_or_training_points"
    )

    affine_summary = residual_summary(affine_vertical_signed)
    trapez_summary = None
    y_after_trapez_candidate = {}
    y_after_trapez_ready = False
    y_after_trapez_payload = {
        "enabled": False,
        "model_name": Y_RESIDUAL_APPLY_MODEL_NAME,
        "terms": [],
        "coefficients": [],
        "normalization": {},
        "max_abs_correction_px": 0.0,
        "source": "pipeline_basis_v1_after_trapez",
    }
    trapez_payload = {
        "enabled": False,
        "params": {},
        "plausibility": {},
        "support": trapez_support,
        "supported": bool(trapez_supported),
        "reason": trapez_support.get("reason_before_fit") if not trapez_supported else "not_fitted",
    }

    if trapez_supported:
        try:
            trapez_params = fit_pipeline_trapez_projective_model(left_mid, right_mid, left_gray.shape, train_idx)
            trapez_plaus = pipeline_trapez_plausibility(left_gray.shape, trapez_params)
            left_trap, right_trap = apply_pipeline_trapez_projective_to_points(left_mid, right_mid, left_gray.shape, trapez_params)
            trapez_vertical_signed = right_trap[:, 1] - left_trap[:, 1]
            trapez_summary = residual_summary(trapez_vertical_signed)
            affine_holdout_summary = residual_summary(affine_vertical_signed[holdout_idx]) if len(holdout_idx) else None
            trapez_holdout_summary = residual_summary(trapez_vertical_signed[holdout_idx]) if len(holdout_idx) else None
            trapez_holdout_better = _holdout_summary_is_better(affine_holdout_summary, trapez_holdout_summary)
            trapez_ready = bool(trapez_plaus.get("plausible", False)) and bool(trapez_holdout_better)
            trapez_payload = {
                "enabled": bool(trapez_ready),
                "params": trapez_params,
                "plausibility": trapez_plaus,
                "support": trapez_support,
                "supported": True,
                "reason": (
                    "ok" if trapez_ready
                    else "hard_plausibility_failed" if not bool(trapez_plaus.get("plausible", False))
                    else "holdout_not_better"
                ),
                "metrics": {
                    "vertical": trapez_summary,
                    "affine_holdout": affine_holdout_summary,
                    "trapez_holdout": trapez_holdout_summary,
                    "holdout_better": bool(trapez_holdout_better),
                },
                "max_relative_y_correction_px_fullres": (
                    float(trapez_plaus.get("max_relative_y_correction_px_analysis", 0.0) or 0.0)
                    / max(1e-12, float(analysis_scale))
                ),
            }
            if trapez_ready:
                y_after_trapez_candidate = _fit_y_residual_candidate(
                    Y_RESIDUAL_APPLY_MODEL_NAME,
                    Y_RESIDUAL_MODEL_SPECS[Y_RESIDUAL_APPLY_MODEL_NAME],
                    left_trap,
                    right_trap,
                    trapez_vertical_signed,
                    left_gray.shape,
                    analysis_scale,
                )
                y_after_trapez_ready = _holdout_model_is_better(y_after_trapez_candidate)
                y_after_trapez_candidate["auto_enable_holdout_gate"] = bool(y_after_trapez_ready)
                y_after_trapez_payload = _pipeline_y_payload_from_candidate(
                    y_after_trapez_candidate,
                    enabled=y_after_trapez_ready,
                    source="pipeline_basis_v1_after_trapez",
                )
        except Exception as exc:
            trapez_payload = {
                "enabled": False,
                "params": {},
                "plausibility": {},
                "support": trapez_support,
                "supported": True,
                "reason": f"fit_failed: {exc}",
            }

    # Default-Pipeline für Speichern/Status: Trapez, wenn es trägt; danach y_quad
    # nur als Restpolitur nach Trapez. Ohne Trapez wird y_quad direkt nach Affine
    # als Fallback genommen.
    pipeline_trapez_enabled = bool(trapez_payload.get("enabled", False))
    if pipeline_trapez_enabled:
        pipeline_y_payload = y_after_trapez_payload if y_after_trapez_ready else {
            "enabled": False,
            "model_name": Y_RESIDUAL_APPLY_MODEL_NAME,
            "terms": [],
            "coefficients": [],
            "normalization": {},
            "max_abs_correction_px": 0.0,
            "source": "pipeline_basis_v1_after_trapez_disabled",
        }
        if y_after_trapez_ready:
            pipeline_summary = y_after_trapez_candidate.get("vertical") or trapez_summary or affine_summary
            pipeline_model_label = "Affine + Vergence + yQuad"
        else:
            pipeline_summary = trapez_summary or affine_summary
            pipeline_model_label = "Affine + Vergence"
    elif y_residual_apply_ready:
        pipeline_y_payload = y_residual_apply_payload_affine
        pipeline_summary = y_residual_apply_summary or affine_summary
        pipeline_model_label = "Affine + yQuad"
    else:
        pipeline_y_payload = {
            "enabled": False,
            "model_name": Y_RESIDUAL_APPLY_MODEL_NAME,
            "terms": [],
            "coefficients": [],
            "normalization": {},
            "max_abs_correction_px": 0.0,
            "source": "pipeline_basis_v1_disabled",
        }
        pipeline_summary = affine_summary
        pipeline_model_label = "Affine"

    pipeline_basis = {
        "basis": ZONE_PROBE_ID,
        "grid_audit": "3x3",
        "mesh_warp": False,
        "quadrant_gate": False,
        "trapez_supported": bool(trapez_supported),
        "trapez_ready": bool(pipeline_trapez_enabled),
        "trapez_reason": trapez_payload.get("reason"),
        "trapez_support": trapez_support,
        "trapez_apply": trapez_payload,
        "y_quad_after_affine_ready": bool(y_residual_apply_ready),
        "y_quad_after_trapez_ready": bool(y_after_trapez_ready),
        "y_quad_after_affine_payload": y_residual_apply_payload_affine,
        "y_quad_after_trapez_payload": y_after_trapez_payload,
        "pipeline_model_label": pipeline_model_label,
        "note": "Affine-LMS -> Trapez/Vergence ohne Quadranten-Gate -> y_quad neu auf Rest; ohne Trapez y_quad nach Affine als Fallback.",
    }

    vergence_model_basis = {
        "basis": ZONE_PROBE_ID,
        "actual_output_model": pipeline_model_label,
        "candidate_ready": bool(vergence_candidate_ready),
        "support_rule": "total_inliers_only_for_legacy_vh_diagnostic_no_quadrant_gate",
        "vergence_v_candidate_px": float(vergence_v_candidate_px),
        "vergence_h_candidate_px": float(vergence_h_candidate_px),
        "summaries": candidate_summaries,
        "note": (
            "Legacy V/H values are diagnostic only. Pipeline v4 uses the controlled trapez/projective "
            "stage without a hard quadrant gate."
        ),
    }

    y_residual_model_basis = {
        "basis": ZONE_PROBE_ID,
        "actual_output_model": pipeline_model_label,
        "candidate_names": list(Y_RESIDUAL_MODEL_SPECS.keys()),
        "candidates": y_residual_candidates,
        "support": _residual_model_support_summary(left_mid, left_gray.shape),
        "pre_affine_vertical": residual_summary(pre_affine_vertical_signed),
        "affine_vertical": residual_summary(affine_vertical_signed),
        "horizontal_disparity": {
            "centered_summary": residual_summary(horizontal_centered),
            "corr_affine_vertical_vs_horizontal_disparity": _safe_corrcoef(affine_vertical_signed, horizontal_centered),
            "corr_pre_affine_vertical_vs_horizontal_disparity": _safe_corrcoef(pre_affine_vertical_signed, right_in[:, 0] - left_in[:, 0]),
            "note": "Horizontal disparity is used here only as diagnostic/explanatory information, not as an x-error target.",
        },
        "model_policy": {
            "output_applies_candidate": bool(y_residual_apply_ready),
            "applied_candidate": Y_RESIDUAL_APPLY_MODEL_NAME if y_residual_apply_ready else None,
            "visible_model_status": pipeline_model_label,
            "note": "This Basis applies y_quad when ready and saves an Affine comparison output; y_quad_disp_diag remains diagnostic only.",
        },
    }

    correction = {
        "vertical_shift_px": float(vertical_shift_px),
        "rotation_deg": float(rotation_deg),
        "scale": float(scale),
        "vergence_ready": False,
        "vergence_v_px": 0.0,
        "vergence_h_px": 0.0,
        "vergence_candidate_ready": bool(vergence_candidate_ready),
        "vergence_v_candidate_px": float(vergence_v_candidate_px),
        "vergence_h_candidate_px": float(vergence_h_candidate_px),
        "zone3x3": zone3x3_diagnostics,
        "vergence_model_basis": vergence_model_basis,
        "y_residual_model_basis": y_residual_model_basis,
        "pipeline_basis": pipeline_basis,
        "trapez_apply": trapez_payload,
        "y_residual_apply_affine": y_residual_apply_payload_affine,
        "y_residual_apply_after_trapez": y_after_trapez_payload,
        "y_residual_apply": pipeline_y_payload,
        "affine_fit_method": affine_fit_method,
        "vergence_fit_method": "least_squares_residual_basis_only" if vergence_candidate_ready else None,
    }

    residual_for_report = affine_vertical_abs
    applied_mean = pipeline_summary.get("mean_abs") if pipeline_summary else None
    applied_median = pipeline_summary.get("median_abs") if pipeline_summary else None
    applied_p90 = pipeline_summary.get("p90_abs") if pipeline_summary else None
    applied_p95 = pipeline_summary.get("p95_abs") if pipeline_summary else None
    applied_max = pipeline_summary.get("max_abs") if pipeline_summary else None
    if applied_mean is None:
        applied_mean = float(np.mean(residual_for_report))
    if applied_median is None:
        applied_median = float(np.median(residual_for_report))
    if applied_p90 is None:
        applied_p90 = float(np.percentile(residual_for_report, 90))
    if applied_p95 is None:
        applied_p95 = float(np.percentile(residual_for_report, 95))
    if applied_max is None:
        applied_max = float(np.max(residual_for_report))

    return {
        "method": method_upper,
        "model": pipeline_model_label,
        "offset_x": 0,
        "offset_y": int(round(vertical_shift_px)),
        "rotation": float(rotation_deg),
        "scale": float(scale),
        "correction": correction,
        "matches": len(good_matches),
        "inliers": int(mask.sum()),
        "residual_vertical_mean": float(applied_mean),
        "residual_vertical_median": float(applied_median),
        "residual_vertical_p90": float(applied_p90),
        "residual_vertical_p95": float(applied_p95),
        "residual_vertical_max": float(applied_max),
        "residual_horizontal_mean": float(np.mean(horizontal_abs)),
        "coverage_percent": coverage_percent,
        "vergence_ready": False,
        "vergence_candidate_ready": bool(vergence_candidate_ready),
        "vergence_v_px": 0.0,
        "vergence_h_px": 0.0,
        "vergence_v_candidate_px": float(vergence_v_candidate_px),
        "vergence_h_candidate_px": float(vergence_h_candidate_px),
        "zone3x3": zone3x3_diagnostics,
        "vergence_model_basis": vergence_model_basis,
        "y_residual_model_basis": y_residual_model_basis,
        "pipeline_basis": pipeline_basis,
        "trapez_apply": trapez_payload,
        "y_residual_apply_affine": y_residual_apply_payload_affine,
        "y_residual_apply_after_trapez": y_after_trapez_payload,
        "y_residual_apply": pipeline_y_payload,
        "affine_fit_method": affine_fit_method,
    }

def _fit_vertical_ransac_filter(
    anchor_points: np.ndarray,
    right_points: np.ndarray,
    left_points: np.ndarray,
    image_shape: tuple[int, int],
    threshold_analysis_px: float = 3.0,
    max_iters: int = 3000,
) -> dict:
    """RANSAC candidate that scores only vertical residuals.

    It fits dy = right_y - left_y as a low-order plane over the image:
    dy ~= c + ax + by. Horizontal disparity is deliberately ignored during
    inlier scoring because it is scene depth, not vertical stereo error.
    """
    pts = np.asarray(anchor_points, dtype=np.float64).reshape(-1, 2)
    rp = np.asarray(right_points, dtype=np.float64).reshape(-1, 2)
    lp = np.asarray(left_points, dtype=np.float64).reshape(-1, 2)
    n = min(len(pts), len(rp), len(lp))
    pts = pts[:n]
    rp = rp[:n]
    lp = lp[:n]
    if n < 8:
        mask = np.zeros((n,), dtype=bool)
        residual = np.zeros((n,), dtype=np.float64)
        return {"ready": False, "mask": mask, "residual_y_analysis_px": residual, "coefficients": []}

    h, w = image_shape[:2]
    cx = (float(w) - 1.0) / 2.0
    cy = (float(h) - 1.0) / 2.0
    x_norm = (pts[:, 0] - cx) / max(1.0, float(w))
    y_norm = (pts[:, 1] - cy) / max(1.0, float(h))
    X = np.column_stack([np.ones(n, dtype=np.float64), x_norm, y_norm])
    dy = rp[:, 1] - lp[:, 1]

    rng = np.random.default_rng(1337)
    best_mask = None
    best_score = (-1, float("inf"))
    indices = np.arange(n)
    iterations = int(min(max_iters, max(300, n * 3)))
    for _ in range(iterations):
        sample = rng.choice(indices, size=3, replace=False)
        try:
            beta = np.linalg.solve(X[sample], dy[sample])
        except np.linalg.LinAlgError:
            continue
        residual = dy - X @ beta
        abs_res = np.abs(residual)
        m = abs_res <= float(threshold_analysis_px)
        count = int(np.sum(m))
        if count <= 0:
            continue
        med = float(np.median(abs_res[m]))
        score = (count, -med)
        if best_mask is None or score > best_score:
            best_mask = m
            best_score = score

    if best_mask is None or int(np.sum(best_mask)) < 8:
        # Robust fallback: ordinary least squares over all matches, mainly so
        # diagnostics still contain meaningful residuals.
        beta, *_ = np.linalg.lstsq(X, dy, rcond=None)
        residual = dy - X @ beta
        mask = np.abs(residual) <= float(threshold_analysis_px)
    else:
        beta, *_ = np.linalg.lstsq(X[best_mask], dy[best_mask], rcond=None)
        residual = dy - X @ beta
        mask = np.abs(residual) <= float(threshold_analysis_px)

    return {
        "ready": bool(int(np.sum(mask)) >= 8),
        "mask": mask.astype(bool),
        "residual_y_analysis_px": residual.astype(np.float64),
        "coefficients": [
            {"term": "constant", "coefficient_analysis_px": float(beta[0])},
            {"term": "x_norm", "coefficient_analysis_px": float(beta[1])},
            {"term": "y_norm", "coefficient_analysis_px": float(beta[2])},
        ],
        "threshold_analysis_px": float(threshold_analysis_px),
        "note": "Diagnostic y-only RANSAC candidate: scores vertical residuals only and ignores horizontal disparity.",
    }

